import { CallMacro } from "../types";
import { CALL_MACRO_FILE_CONTENTS, CALL_MACRO_FILE_NAME, CALL_MACRO_REQUIRE_FILE } from "./deprecated";
import { CALL_MACRO_DIR_EXISTS, CALL_MACRO_FILE_EXISTS, CALL_MACRO_PATH_EXISTS } from "./exists";
import { CALL_MACRO_EXPECT_DIR, CALL_MACRO_EXPECT_FILE, CALL_MACRO_EXPECT_PATH } from "./expectation";
import { CALL_MACRO_HASH_FILE } from "./hash";
import { CALL_MACRO_READ_FILE, CALL_MACRO_READ_FILE_OPT } from "./readFile";

export const CALL_MACROS = new Array<CallMacro>(
  CALL_MACRO_READ_FILE,
  CALL_MACRO_READ_FILE_OPT,
  CALL_MACRO_PATH_EXISTS,
  CALL_MACRO_DIR_EXISTS,
  CALL_MACRO_FILE_EXISTS,
  CALL_MACRO_EXPECT_PATH,
  CALL_MACRO_EXPECT_DIR,
  CALL_MACRO_EXPECT_FILE,
  CALL_MACRO_FILE_NAME,
  CALL_MACRO_FILE_CONTENTS,
  CALL_MACRO_REQUIRE_FILE,
  CALL_MACRO_HASH_FILE,
);
